server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db?createDatabaseIfNotExist=true
jwt:
  secret: "ThisIsASecretKeyForVenueLinkJWTSigningChangeInProduction123456"
  expiration-ms: 86400000
